name: Image Therapists International
favicon: null
layout_spectrum: 0.6018074627500027
typography_spectrum: 0.983473172178492
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9227331257425249
  lightness: 0.310224685119465
  saturation: 0.7462061773985624
  rhythmicContrast: 0.4093573549762368
purpose: []
